---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: payment-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBjQUo9B35QWWler/CyTQ0UVViqScbdajxY90eKOYnEPcD5R7HNDEXw74llR7WZLNYSz82R5VZZ9NkL09kNywMzLFMeq20BHd/w2Y0O5AFQ1gRJLY61xXzfpiq31ZNBlRqmKo10UEAlBoHwKlHZ0G465YF6nu1RU3X1e6Jeiq1Zc5jHaVoWPNL9Oz9XNPFG88u/rzRH5TNJiksvTPFAoGZkWTNVj4hRgqnKFO0GEVHwaXz85MoI0FAZbXDntsXu5zzrj2aaGXAVQL2FvFBcPu40twRBXtrrCBRCgy5CqmyY1aOriWYz/XElABJI5DxDQelCWc7bGDvmQK9Vt3y57RO5/PGwDaRtgf9Wj+tTgXT5MsvXdqzVKq3larurPbBQGtnaw2FuZJxA9bJbRO5Q/E83jGORvNISWIPu2nmRYLETXmj38OqK8L6r+DpbqxNZTDJqcmIbr250LC1JaO2WmAv7oZZWpHGGHi8Fu03BxkBIN38ldabCzizmiYRqsWYv0oxbFqcxLJoe8XPgCGMRh+HdedLgaLgeFldqniLJ75KzGjXDyVUYlQW3WY/quunXOB2iyPZmRL71zECaUKJZltmpFsO6XB1c2C/ILvCcjLykIzGtxPnUu/iyMmT4iCrosMO49pVvPl8FUHsyhAAfkV2n+Rk+jWrGqu+v8Q7VJZH/TPX4KSo34lBT4/t/N/q9eQM6C3AknOzb6X+mug==
    username: AgAHl8ZeJUQtRSNWBfYaD+TM/XyP+XSOXF1i9nG4l5b+P6Da3HW0oui78UOQwtFYKwaEBlc1/hZsR85suUe0hDXrg3TtosjM2FKgjs1FT1LYtKlWfMAwbXnJCdx0lwM9eqTIgvESwKBvJjnxo/CeEZ0ZCIOsnL3LviyVcAkibUCH7X7g/yZFjdQ8vnynKnUBJsCa8Lfv9mC0raHFeBGlAGoIlWBgFB0K6eUrwiNL1NdzPZ1Brm05GE8JCAd6Zvj67MIUMtxc4FfhRhdVmNEk4Yu853Vop6t/SCBdz6RitFe2Vg2DuGX5jXMR9CQcE1PMOjrMEIX0+RziiDGQO3E2lkejmRkr4KJ4sMkYewY4pyGm79O9IwxE+FHljIgp0iCnTmH1sipmkfMSmZUr/+8Yh6R/ToF16OzENKgjH3JftQfzZNMf1KJ4vcrKU24zq/PDT4UucPBCobrCJQrbhvjMQGbAFg/2g8IJpAZt2KzNOoVulfolLg9C7XkpP1mI4Ckb9H0uHqo5VabfYMbT6dINwiUeAifiHZAyhXTENB9gLWbLCzVPClXOExYPknzaiHxoaCoYFEceTYlGn9AC9ohuqacseTvGRzXowSVoE7THqY4fJe/H3/DP4Dq8rUe6htFT3Vhj20PtI+10/pTSTgrAgZmLVqwQIUMHP8A1HvQ0J0mA+fUaTYiJNWfz4AauMIJxw04IOJQBMvGwQ5Mksw==
  template:
    metadata:
      name: payment-db-secret
      namespace: default
