apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-mongodb
  template:
    metadata:
      labels:
        app: audit-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: audit-db-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: audit-db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: audit-mongodb-service
spec:
  selector:
    app: audit-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017