---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: audit-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgCHfrEbuDfLEB2Zzs6bYpvaDk93gowIf1GBJEalLav/GCQy3/QMPBbZQbSQdY7xee+SgnHm/dVtKpa505RIo4WNSCFyZnVFARuzDAnlmf5YsXxoNpGS7rUzyHlVCRL7+n1VeGxbyRoO+bxovPBgWoZG+thqlfQqbQrM2aCneBLEZm0/KxyxpNt6B2pesqOkZTOc0huTMbbh4wm99aAiLffAVvtDGizQ6uQImeft56KfVccfPlOqBSa8Nnyz0D7n0x3UjPBBqQVCLQ7vgkyKupSPdE9iZwDBOV0p/BeaUhcCU0iCAh9zEf7rzw29krMhSxTwosqaDm8dvkxgks10y2UC2TuPN1TGof6Rz0Y27fA/NC2o0XEMJwUXb/W+DxzP1tzH6rls7mwdD+CJkJDg/8ElnTmelY6Fse0gl2YUBgAa93Ewq7ocQbS89sUWEAEoACgTibbtgH9tMifZ1JQYRH2JIItBR3J7FaoYUNVVSMXFAQCXS8R43pqFg/63Nmpi7c5hdGVkj1q+GslYnJnqEsy4pfajXFNzIMDoy3de0ACWBIIdWHLOkvQPIJ7UCGqgtJsVepsPqAGw5vreQsPcXTYUHerD6J12FdPWV+dpgiWX/vcT2q+XF45MT8XwaePbfyWZpGgrUYfgGOz+CD8XTTCwTzWnJ1rgJ3B/JGV4LBnSZnl6wFe1VpgGUjorlEhKsGZ9Fad1pi1BOCk=
    username: AgAldq8194XLW/Ty4Aw5HyuyB+3UMOKGeympnN4ODpLmYPZXoYDkrYJLEt2uPn/HpSWhEm4Yfx5mBmp/S5Rb2JtkTF3J9vPl14mh8qA0QBt2wuJ6xDbUg+nzPu13l6jGUEhdWECVAWqKM7xG0+2URSTIHBUL1UNcQpta7mnlaYkMkA9pPaZA7bJGrs4NpwCeKAjt6jc0cELyQHEcBarp+I4HxiGamyAmQXibR9qLwmOP6hvZfUngbb9Bvabc5iiBUVj75egC/tWLeWeSUEVIWVIeVmo9gi63UiPILhyTBopDu0XRVMlQoIuv3a/nEJIN4rY1oHYim2y/yiNHjvsMe2/3D2+g/vGf6UkQ9XRx9AVoXy3kVr7oPcft+2kE1mTfo2eTbA/ntQVcSqXuWyP5Yai2BFSZ/RXqjZDoeOKqmJK8ZA+1svhJdVAy5W1qfov5ZCqfJqsrFQpyULOHnAJck4RLQkvtZ7mSceTb/MqG50SifDeW4v2W3j9RT2ivPU11lTthrrpnmRot7lHqpMytcuxOGnWEYhKHl53ZiWVL321bGezuBjdPUbxdjq2N8bI+qwIVp/WsWqgTx53+zQrlfXkFYVYSOoDFMv75EILkAeuNR785fL/cBbhoikXyr25A/wkcCeSu7vHZ8AS0PF6k2IlI91XV/bGW66qESCZfqczBQa5pZ3urcoLe/xrdVSVMl1wrjeX1PBOi6ZU=
  template:
    metadata:
      name: audit-db-secret
      namespace: default
