apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: kamilkowalczyk8/bank-audit-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://admin:admin123@audit-mongodb-service:27017/auditdb?authSource=admin"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  selector:
    app: audit-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080