spring.application.name=auth-service

# ---- ARGON2 KONFIGURACAJ SEC
bank.security.argon2.salt-length=16
bank.security.argon2.hash-length=32
bank.security.argon2.parallelism=1
bank.security.argon2.memory=65536
bank.security.argon2.iterations=3
# ---- ARGON2 KONFIGURACAJ SEC


#Konfiguracaj JWT
jwt.secret=U3VwZXJUYWpueUtsdWN6QmFua293eURvR2VuZXJvd2FuaWFUb2tlbm93MjAyNiE=

# Czas ?ycia tokena w milisekundach (15 minut = 900000 ms)
jwt.expiration=900000