server:
  port: 8081

spring:
  application:
    name: auth-service

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# ARGON2 Konfiguracja
bank:
  security:
    argon2:
      salt-length: 16
      hash-length: 32
      parallelism: 1
      memory: 65536
      iterations: 3

#Konfiguracaj JWT
jwt:
  secret: U3VwZXJUYWpueUtsdWN6QmFua293eURvR2VuZXJvd2FuaWFUb2tlbm93MjAyNiE=
  expiration: 300000 # Access Token: 5 minut
  refresh-expiration: 86400000 # Refresh Token: 24 godziny
