spring.application.name=auth-service

# ---- ARGON2 KONFIGURACAJ SEC
bank.security.argon2.salt-length=16
bank.security.argon2.hash-length=32
bank.security.argon2.parallelism=1
bank.security.argon2.memory=65536
bank.security.argon2.iterations=3
# ---- ARGON2 KONFIGURACAJ SEC


#Konfiguracaj JWT
jwt.secret=U3VwZXJUYWpueUtsdWN6QmFua293eURvR2VuZXJvd2FuaWFUb2tlbm93MjAyNiE=

# Access Token: 5 minut (300 000 milisekund)
jwt.expiration=300000

# Refresh Token: 24 godziny (86 400 000 milisekund)
jwt.refresh-expiration=86400000