spring:
  kafka:
    bootstrap-servers: bank-kafka:29092
    consumer:
      group-id: notification-group-v4
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: mailhog
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

cloud:
  aws:
    s3:
      endpoint: http://minio:9000
      access-key: admin
      secret-key: adminhaslo
      bucket: bank-documents
      region: us-east-1

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


integrations:
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL:}
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL:}