---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: account-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBVzbMk0R6Yxkv7re7I2sbg9ioZYK5PDryXQlaSPiE9OcABn5agbbko0osFLU8Po2GrsdbQ8PuBhdMuc2yq9Iq++lNJRaoSTaCbJhAv6gonqQ1U1aYid4LGtaWzqBBiA75J/Q+0NyJZ19Viu1zH9BHNXB8FMMDC8U7WJbw4PVKU+WD2VTVz9QTm2DqBGKQx3mVWPjhi0Uc8xQlB5w5AdR/wKusRd+smCgCUgrD8fWNVWH7X63GvkOrEDgjLIK1vqhCf9Wn6KeGg1iUJQ9fD8UERA8IXzB3XYg09ku/6+uUNll7t+xsXbdvyhFZ2qH+rSTo9bXD/KJd01yfT9rmFpyDbMoYhvaSCRu+kEzAGuH7ypnuHDv2CoW5HNq6h1bmokLPBX/aiPkRuVRs9LSzBCBMTijSiNx3nsC1GQ/gmI5GRX8gGNy2UqjRegMibKhaFXOob2j/z/RD4lBQ7yVC/8OSYY7gU7FTO5eDR/OHJAUcqnHsetwPePYQl9z1DBqpENqeMCL0sqO68uXuc0W9QelP+LhLnt9lUh3I4ffEUvpOoaRFN659wFbm4j5wVFNX7hCPYHQeoI1Wl1Ru+bEdavyCGNUcwqr8zd6z3EvauBiclgnTcnY3qKmw3XYv//vh5KCQ0X1OKkH38K6+0ApMf1Sg6oqLuO1JzhLpOezuD8j8E63bXCdrk5scz8CEZUSsY1DMtgGecWRCai24Tng==
    username: AgA8ajwSarTG2cnDQVXqL+G2q3S3tL5OyijkwbZUXDTzSn4cutwHyIGNPLBmdn60R1q63x7GYyRA8dRgga69XF7IWvPHsRXgNqOs/rX050qjnp44icXImu5Wi8kGlTvTbFxnknVYKSLtWpkrAI2ZzHLvlQOsg0WyJfochz9VVitBNKKGImXJ8m0Ij7C74X4QmyGbAXfKYvrrpK6M3krJyamnHtALENW/OG7ijsyzPYXE23ymNJzpzRePbu8vjS1ys+QiE0o+/mQC3FRl/sxOEVNNlR4+UQSfuS4j7R5B6pyuZHOrt1zSJ4bn5mlK+tpigtJ4JBseRdXB9nNxZoqtQBUQC25uEpi7NgQWsZ79wl4nePSoOOC1MddPexuEJVRjZhugYhg2IJr2PHAh3sUN3Slhq5c5gOrRVmJhUypa05zJ3bw1ObZ8pKB1F5j1z4SxJILOfqzlub7XN56cfjBu6oToJbgd8eDyF+lTSDTWwdl/kPqTz8tNzCm1eI2e8e541y8W/VHHtEHtX9ujdjTZ7vuIF6P+S6x8iuqGzrGJ/eZQ5sggFbu9I62B8GEBTftNg4xJWf/R+VjinqmTTw5CTQDo33blqa3CTtvf3xIC7UnZSxI09Yy9hOj8xHvy0ohCUh0W1RkJVz4vfkveb48K5IKZigc/x4vO0NRx+8Yb8qslUnUwvLLI8CpKB2Auid9GN+8WXebnZ9QDMkozoQ==
  template:
    metadata:
      name: account-db-secret
      namespace: default
