apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: kamilkowalczyk8/bank-account-service:latest
          #imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://account-db:5432/accountdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "accountuser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "accountpass"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084