---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fraud-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgA1Su3lMJsVpCv8xLGRyui8eyUZhwjG01g37x1Ieead4hM1jS/Lz5SWR7AsVucMkt7dhD1VA6hxnr1ljhgDv3VCLxKOYBoZrUBAId5CSBmwTib2OXmPvIy8o4l6ELZ1e3nkMEsGOGf9mA1aUWPjoEdfkellfzxm5c3VldEkZCtyEeRFYMEOwot6lsZQrwt1Z3aDP38XVQqlndmIb5Hcq0bZ9ln/Rj8+AEvpzk3Laerv+a7v4AVxy+y4HXtvPAV/v2QsKlg0jRiIAAsb8sfoEo9haKKjTokGaPsBu3lb4YEOF02lPMHVW84bX0s83IpKoETk4T8cRymPqpeOWYCiJkvoe2lMefuBUX3388H6W2VOdDj+dxwXYcsVcV7q4To+fR3rRniN+O41x0f9cLcJ1lZZr3Ad99KIiEzEWBzMUCLcquqNJR9vaCNeJkF39bXfUDz581vbjZABJJ2byHr/Ifiv9tbj+C+OBQp8DngtLzyVlM2VHXz4Jk0moO0aM0tYdBx0qdiFfsQO1g+qUZQWNVVmiKC8zbT9w+ARTDM9fHhHML1QPpWrXyBUrbXAXmydQr9x/eJh/FEwPFQuyNLkdoFlDj/6hx4e1LTyPQFHDX9OBo5inG7gotINqunit9Ez/W9gSo0P8lpUeV/FhujPLBQKkdgNMGc9d9o97uLLDR+W5t0Wy/KFRPAEMLEtJNoiEI11rn5SdbveOto=
    username: AgASsPlEssmtkClF0Jhm9+FFl2GYlV3/Fkcn1TQkQFxKeeW8FJjMpH0981vxDsTWTfa8oi7kwPubp6mUNfpajjoYftozgUgG1MYE35es15S3sYYRc76PjOo7fcaEhQcRtkGgfvcWI9b3XNkag3MqnLAnJbr2PtmMR6JnU13ZtdJb1az7upp1gRFP5dTY7xRT0jh09maiGJHdV5NZs/M2r7qHfP5OYqMV62d+ISPULw7L+a86w73hz7pw7T2hjtKXqLN9F2xK6NKETaQpc5g5piM9HpkfvvG7fvvCiIrJRCg1QpgGe+522JQUuErw+EiUJmGohr0II8wwOjg98DJy+Wf34NL8bC1bvn4plVLG68JpIxGxWN3Uk0sh+Rh/yutPAC1jnMJdUyfodI85mHVY55OPpU0Lif6rHchSR2FtcCj7kGtpYwHLF3DYaSZmnw1wcFZn22b/ZdtnlUL/Svy4huOO4O2IqkwItiqoL7Y4fwHG6lP4UpAI/b1BQ/6GCZ6pR5yUliFCVteUqVqoBFYCTDsybOJwWcAZQYwq5C6GYB5DPNwuYkvGYLFyTsVf/afzv3mLuvsl+UXhiUqj6RP/PNYElHRAD7PIHFzahCQU1jPXbkpVQ21m0oe560qhOBRgWlwUJh+oPD9SVJOzNdJxvGxpPnU/tPYDZd9rICjjFbR3tYtHdrfL1UKUqHr/YfkwAlK4LouDIxXAhiE=
  template:
    metadata:
      name: fraud-db-secret
      namespace: default
