apiVersion: apps/v1
kind: Deployment
metadata: { name: card-service-deployment }
spec:
  replicas: 1
  selector: { matchLabels: { app: card-service } }
  template:
    metadata: { labels: { app: card-service } }
    spec:
      containers:
        - name: card-service
          image: kamilkowalczyk8/bank-card-service:8247e51796e60c841a8eb7a91236a8a2bde538d9
          imagePullPolicy: Always
          ports: [ { containerPort: 8087 } ]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://card-db:5432/carddb"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: card-db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: card-db-secret
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092
            - name: SPRINGDOC_SWAGGER_UI_ENABLED
              value: "false"

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata: { name: card-service }
spec:
  selector: { app: card-service }
  ports: [ { protocol: TCP, port: 8087, targetPort: 8087 } ]