---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: card-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgCjHcKw+ebj/21HTZepUlIuFTInZITCPh7owvdeLpJe95+MA1HOQiWVkey2ezt05BBTLs7JhqmiQrFjzBXE+TDnx/zorbEw3dMP1lasNMhAPNPmok5w5qHUkJkf3eZr1HQXiTOzNcFoVqmD1SEjb3NPq9I/sQikBFMxfB8GwVv7oq7tl2doJpSLbwXiPWb32ehYjUJFbkDo6FHE8pR5jKf2EMtpTgG0c6tdal3xKdHui0MpedSJQF9LELb5ttklzYGg+B5BT7vjgLl++Ls+XIhpLgA5ad02bCE0S5EXHEXrGDBGxchiHrGCkaMM0wF9sIu8evGtI0Hi1wzAB4TbtAndpiHqQsOt1SxxZiM/ghbbtWgFu+xT9jejvTHlasrMqYPHZ1/mFdsbK7qt9yHBblcYAV6eFm1JW+e/PvZI0hwU3/R0zQt/1GQdDUpNnGf4K7fOY/ER/OQVZXX18pBScHRwVrxvXg6hAFUJ25LMZLRhlazkjcJLkuVrljQzPjt3ssuI+w5ZSQp3baOSoQfoZBrzRhOv8XxnOwPHmRghd99Jrpd6m+Ab4OkrG+v2PY3SIvx0a1c8PONwb4idXwYcMXTOqt/4yh7lvZt7wiU1A7YsTYlkgNO+pDmDZxwb55m7GejXqE5g8Le4D8e0jCKP1eZVbYzUZdmcYFp4YMHjLJ4IDMMJdLcUcY2xGJ8gKixXzfqE1NmlMFF8Mw==
    username: AgBFDL/thlxMlhkR0e4k0l2M0WSfcJGkaLy8r4bRvayWB41NlDwyRHCoNzxQEV9df74qVOZzx8jsS4VZxbIX2RxW26Y4noDWF4kb+vBOzw9d0mTQmNbthK6N/uItYPc2e9ldmi2VkvF5oZhrnPfI2VXdrE/b4RN+7vCS3X5+ofmV3Y/Avqwog3+7fBqNmd5gkbg1jxQBbarA85eOd0PcvBkeARvnbSWNvbW9SCIa8AnNVidJ+A2NnqGstuBo29LcuI2lBMoVIF4hy3JLauc2kr4F1alO7GxMGztgWC2ksb9ZkfGvt1iHfpG/P3NqyyUKl4fIbWgpQSUnVAMwOabMHP+eFg6/wy9WzA/IqmLsXQIjRCRoQ/Q0Ea93YiJ0NdkmnZx19Up6QmDD0b+6g1N0GXB+WMn9j7RKWfsoFyBpQrJKjLz3vGfysioIK2r85onxM1IyqeRUlQQ2KUnWUmsVEX1MThjK5YZTKZbIDYVoj8v6Xte6o9vXUctqPNOrvr0jaU68cOJ/xCiOVg3FamGXJzvYJKDYdSHbd4DlFwVIjcYDMf59KVkq4F17yYMsn2BRhgkWCAoJlkxsuyEQcZSExQispR6Fnx7JJNzs98DPD+CnWNJ+SoHSm34XJiSsEc+3rDbzzNLsX7BAoMc9lsclRUo8nDzjwogiq6ND6epcBdmamGKSwsQjb7fC1V2IYYnEVakBqrdMvgqQhg==
  template:
    metadata:
      name: card-db-secret
      namespace: default
