apiVersion: apps/v1
kind: Deployment
metadata: { name: card-db-deployment }
spec:
  replicas: 1
  selector: { matchLabels: { app: card-db } }
  template:
    metadata: { labels: { app: card-db } }
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports: [ { containerPort: 5432 } ]
          env:
            - name: POSTGRES_DB
              value: "carddb"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: card-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: card-db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata: { name: card-db }
spec:
  selector: { app: card-db }
  ports: [ { protocol: TCP, port: 5432, targetPort: 5432 } ]