services:
    auth-postgres:
        image: postgres:16
        container_name: auth-postgres
        environment:
            POSTGRES_DB: authdb
            POSTGRES_USER: authuser
            POSTGRES_PASSWORD: authpass
        ports:
            - "5454:5432"
        volumes:
            - auth-postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
            interval: 5s
            timeout: 5s
            retries: 5

    customer-postgres:
        image: postgres:16
        container_name: customer-postgres
        ports:
            - "5455:5432"
        environment:
            POSTGRES_DB: customerdb
            POSTGRES_USER: custouser
            POSTGRES_PASSWORD: custopass
        volumes:
            - customer-postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U custouser -d customerdb"]
            interval: 5s
            timeout: 5s
            retries: 5

    account-postgres:
        image: postgres:16
        container_name: account-postgres
        ports:
            - "5456:5432"
        environment:
            POSTGRES_DB: accountdb
            POSTGRES_USER: accountuser
            POSTGRES_PASSWORD: accountpass
        volumes:
            - account-postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U accountuser -d accountdb"]
            interval: 5s
            timeout: 5s
            retries: 5

    card-postgres:
        image: postgres:16
        container_name: card-postgres
        ports:
            - "5458:5432"
        environment:
            POSTGRES_DB: carddb
            POSTGRES_USER: carduser
            POSTGRES_PASSWORD: cardpass
        volumes:
            - card-postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U carduser -d carddb" ]
            interval: 5s
            timeout: 5s
            retries: 5

    api-redis:
        image: redis:7-alpine
        container_name: api-redis
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    kafka:
        image: confluentinc/confluent-local:7.5.0
        container_name: bank-kafka
        ports:
            - "9092:9092"
            - "29092:29092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://bank-kafka:29092,EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - "1025:1025"
            - "8025:8025" # port dla mnie panel

    # --- SERWISY ---------------------------------------------------

    auth-service:
        build: ./auth-service
        container_name: auth-service
        ports:
            - "8081:8081"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - JWT_SECRET=U3VwZXJUYWpueUtsdWN6QmFua293eURvR2VuZXJvd2FuaWFUb2tlbm93MjAyNiE=
        depends_on:
            auth-postgres:
                condition: service_healthy

    customer-service:
        build: ./customer-service
        container_name: customer-service
        ports:
            - "8082:8082"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        depends_on:
            customer-postgres:
                condition: service_healthy

    account-service:
        build: ./account-service
        container_name: account-service
        ports:
            - "8084:8084"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        depends_on:
            account-postgres:
                condition: service_healthy

    api-gateway:
        build: ./api-gateway
        container_name: api-gateway
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        depends_on:
            api-redis:
                condition: service_healthy
            auth-service:
                condition: service_started
            customer-service:
                condition: service_started
            account-service:
                condition: service_started
            onboarding-service:
                condition: service_started

    onboarding-service:
        build: ./onboarding-service
        container_name: onboarding-service
        ports:
            - "8083:8083"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        depends_on:
            - kafka
            - auth-service
            - customer-service
            - account-service

    notification-service:
        build: ./notification-service
        container_name: notification-service
        ports:
            - "8085:8085"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        depends_on:
            - kafka

    ai-analyzer-service:
        build:
            context: ./ai-analyzer-service
        container_name: ai-analyzer-service
        ports:
            - "8086:8086"
        environment:
            - SPRING_PROFILES_ACTIVE=docker

    card-service:
        build: ./card-service
        container_name: card-service
        ports:
            - "8087:8087"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        depends_on:
            card-postgres:
                condition: service_healthy
            kafka:
                condition: service_started

volumes:
    auth-postgres-data:
    customer-postgres-data:
    account-postgres-data:
    card-postgres-data: