server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: local

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer

logging:
  level:
    org.springframework.cloud.gateway: INFO

jwt:
  secret: U3VwZXJUYWpueUtsdWN6QmFua293eURvR2VuZXJvd2FuaWFUb2tlbm93MjAyNiE=