server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: api-redis
      port: 6379

logging:
  level:
    org.springframework.cloud.gateway: INFO

jwt:
  secret: U3VwZXJUYWpueUtsdWN6QmFua293eURvR2VuZXJvd2FuaWFUb2tlbm93MjAyNiE=

services:
  auth:
    url: http://auth-service:8081
  customer:
    url: http://customer-service:8082
  onboarding:
    url: http://onboarding-service:8083
