spring:
  data:
    redis:
      host: api-redis
      port: 6379

services:
  auth:
    url: http://auth-service:8081
  customer:
    url: http://customer-service:8082
  onboarding:
    url: http://onboarding-service:8083
  card:
    url: http://card-service:8087