---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgCXwtbokvJlr3j51QbSVNMomFMxJQzj0LQO/KK1oF60pwcOJeE73alau5kYicTBhBiPx/dkQ7M86DYf/OqlLjHNOjI7ZUPfZpbgdy3crzOxTejNw8KoesSYcLPjanMrVNINV+7LxFkbI/KTtbs7yw+VQpMsi2B3XVCG6yXG9sgTfWR8OzuLxMJi81BRCzcEvr3qvfKNX/Tt+/ps8DqSiE41sLpq16MvfXpkynpWlYoC9pwjxW+dzsBJn1rbArA52EcsQNqysMcm3wNKBnhLZW9Cs3E8qCCebPxCMvYfuk1/Tk1I9ujTQnI7XnT6S3F5wBLhZecnrKMLYczc0alX7eboWfz/uyECKcae40oUPiILERppYuWNw2xMZgBGuRGxEZhgggs38fNlIatq1JD2Jgbw+km8zRIVcd9E4JICZBTPxbNWDfWWE7dfgo7/GknlzClZVQI45MHrQd1CHY0wa35Bqlq74nAciuXshN3K8Bj+tvPFmzP0E7mwSje3iImR7zOG0Is0ZLqda8L53D4+dn/Muxj4D2dOP37Mww5Iw1b8GFgrDh1vouEoehCpJzZVIASAuQVPlkV2kkDmQR4AYU/vixv6NnB0rnwksM96Q3NzKQe7T6ZbbiX69GOvoRuMkPecptIgAx2nEdqlPBNZuhTDS7S2ekvS6mvzG3BMZep4/sgA6APXx7q0ZXxovOcdDeVexq1AfTSbHA==
    username: AgAN9XyMT31QGj2R6HKN4/JQku6swE3ac/XAlF4DBopAoDKZVkTfqNl3FO88iZQedNn0/av+FZ1CJRKd1jGCQ1OpqFr1uBQ9XU37QoDMfo2pTsn/bRqxMqNpKY0RAOJtRckRRm2LpyIe2lP+8Hk2WRQiWH5Th3oxx8mPu7m49Wdd6fPh7fz070gwaBMK6zxt8rHxf9mPexoT0CtKZF6oNVxTOA70nQVYuD08vG587SonnzEfz0HEb9KuTjwSswuFV/4tzFrpp6VRcM/EMbzfbPOueEaDA/udzG9UsdCQS7+iObWOU6B7Ad/MbkDdaCJCZ5yQIFluYXVokCnnQn/YaBVf5MsZU7BZB4rOMjfmhHqh3bbTFTEY8+EEc018Ng6ZzYmv2LLlVyHFb/NQ9nYaYD+/m/Ylv/eeRIxwyEz244GR/iPngdGca18RjTie6IyAJkB+rohB/w1M9sqRRueG4u9OV7Is68MiIDEMqp3zzcHyUb2amCagfa2hxORA1Ae0UPBkW0RWUlIjKBRjT88B/fT0my/gRXfH19RGZ9p8XXNfCsEWs4VgS5M2+qVrwoWcXdwBn/bCMrfFQfOdnsad571g9E/kA0sUMqOH97WTLu9+iTChssH9qwfjjS5rIVcHQ6LJmiGmndZPR014DQlFsig+cT7/JIslQPYU0ybHA5G2ennE8iw28QhOmhXn7YVy1+q3gm0f8crs7g==
  template:
    metadata:
      name: auth-db-secret
      namespace: default
