apiVersion: apps/v1
kind: Deployment
metadata: { name: onboarding-service-deployment }
spec:
  replicas: 1
  selector: { matchLabels: { app: onboarding-service } }
  template:
    metadata: { labels: { app: onboarding-service } }
    spec:
      containers:
        - name: onboarding-service
          image: kamilkowalczyk8/bank-onboarding-service:v3
          #imagePullPolicy: Never
          ports: [ { containerPort: 8083 } ]
          env:
            - { name: SPRING_PROFILES_ACTIVE, value: "docker" }
            - { name: SPRING_KAFKA_BOOTSTRAP_SERVERS, value: "kafka:29092" }
            - { name: SPRINGDOC_SWAGGER_UI_ENABLED, value: "false" }
---
apiVersion: v1
kind: Service
metadata: { name: onboarding-service }
spec:
  selector: { app: onboarding-service }
  ports: [ { protocol: TCP, port: 8083, targetPort: 8083 } ]