spring:
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: bank-kafka:29092

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com
      chat:
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-1.5-flash
          temperature: 0.2

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false