spring:
  datasource:
    url: jdbc:postgresql://payment-postgres:5432/paymentdb
    username: paymentuser
    password: paymentpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: bank-kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

services:
  account:
    url: http://account-service:8084
  fraud:
    url: http://fraud-service:8089