spring:
  application:
    name: payment-service
  profiles:
    active: local

  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8088

# acutator dla dockera
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always