spring:
  kafka:
    bootstrap-servers: bank-kafka:9092

services:
  auth:
    url: http://auth-service:8081
  customer:
    url: http://customer-service:8082
  account:
    url: http://account-service:8084