version: "3.9"

services:
    auth-postgres:
        image: postgres:16
        container_name: auth-postgres
        environment:
            POSTGRES_DB: authdb
            POSTGRES_USER: authuser
            POSTGRES_PASSWORD: authpass
        ports:
            - "5432:5432"
        volumes:
            - auth-postgres-data:/var/lib/postgresql/data

    auth-mongo:
        image: mongo:7
        container_name: auth-mongo
        ports:
            - "27017:27017"
        volumes:
            - auth-mongo-data:/data/db

volumes:
    auth-postgres-data:
    auth-mongo-data: