---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-analyzer-secret
  namespace: default
spec:
  encryptedData:
    gemini-api-key: AgCfUQMCa9MCZ/DJFTQ0ks1YHEbJoudZYN7lARwV5rQulWnghQA4QlLMXQYm0OWOBzCpVcj4+OAeylF9o8Hy0u616dv5A/elisLO5tyJSEHX648JSfj3btNBuWCov5zZ9KvcbtfJxTKELxXc88JyPJjESv1CzZ4BBvQvOq9tBJlfiZI6mDWlAsyx59CcfGMSg3IdgOVTSm5orzHkHK9/Rju0IPG4McfZjRzvdQdDdOdT1mtVvGFiQ+nrxCkfrr5QgabgXSzIanYteI9FDTUPZxjbnuaRp4G9z10xwR+s+ToTsiBU3TCrvWwK1yzIRvA7p0yGQFvAZ2k788HQKZKNilKy9j99zrG1rz6xfCdgxShSd+msFSxGSoA2RUeHwvF9LF6drm4IS+UkWchX72Eku2k8UOzVHZg/tKaPtTV+IsxkknbF7+C3NxUV0+4mWTE+TY7eQeQnHvVg3z9dOnXcaduKUvOoQ8pF6FrtoVajcg1vEZTRWU/4rRtOixQ+sdBIuJraNcyPpVGkZPnk4FMkeCJMp76gEqFMC1JBou6B1qau/sTUD5XsxQ+9Gk5YwVIGFFDRjefQAortGk/HdxKdvomHNUdyoOcvo4xMMl4WFT1zA3X6701lEYF3E/BeGAnh0NfJRMLT7pAbaJomxNCeBaMyh6Gr0yttdAUsvRngvLoZpf7brNES6XDKubB+DBtpzzhTLLA0F9rJtvAxLuOXtQcO05oWV3Jy/Qz5TGEx2hAcqqrGomUC1Js=
  template:
    metadata:
      name: ai-analyzer-secret
      namespace: default
