server:
  port: 8093

spring:
  kafka:
    bootstrap-servers: bank-kafka:29092
    consumer:
      group-id: document-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bank.common.dto"

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

