server:
  port: 8093

spring:
  kafka:
    bootstrap-servers: bank-kafka:29092
    consumer:
      group-id: document-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false