apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: bank-system-customer-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://customer-db:5432/customerdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "custouser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "custopass"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082