---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: customer-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBUxcZRs9KOFJzf/hwhU7gPPVKDOrZDE4yX41Ryn9vZN7lS/XRDKfg5Czdq5LHTiW4pew364Gl/fdkq7re1XXr/sR5CdkEu1ARyHdMeTLUUJ+0sTtizOSpBfUcMJLjEVI+TH802bpNrdr++RpOofAGwtuXNMedQ1vxPLfJ9Iu+uXi76XDtL7WBrnC0U0LU9LVoRZkvFChSRKzRTmW5utXGLYHO9pLW0zV3zjLNMs5WYbnkrRqxpmpav3yKFPTUy0tuKCO8EPkyYhAQKrPqfhlZ2BqG+PgPicdGm8hyTRS/QN2X9FKkFx+h3JGAByh0cC8gUGNnpgOXx7pMAKOQus6A6UVbshycee+8K954efj15W1Yd2OuNWrd/YHbIdC9/5DcLiwu2AVyo7/W/ZQdmErro2AonhgeGuQfYBqH8fSkav1uNhYGA+zimxUf+qrdFA31Kjwvk0Mac11ptUsUqaoLYarL9ERLICH2RdlwGlyddIfdOvljP1opsfZyD1xVzv3YbqJH/UA65052kcFUYwUHaJy5MM0QI8VbIrXCFy8MUM3PIK8J7b05d8aY3Yt3tM+OobXvb8UlGj8VDyzxpa85HwkbI2nV87aUuLbMPDsU6KIwdCKTOKgsmsj5S6a3/giIHg6nrBBmRQKUQIiQf6kJ9ZrkwYAb8iETAFG5pbdMZxYxHkRtF+6OEpL9vISVCPcLE2O1LJiypiaM=
    username: AgA/6qtUKUlpJiolVJO2aBAGLG6BmfKON1J/mmY7WNFfCPvNI30882fFEL8Fy2PQ1Fi5L54Xs7zIXGftrD9Zr6ItlACoPZ02YpJYxWHoOf3z83l41nyCi2wquiDoHeXN3+T4IuTEbyox12kG8XW0wcI12F/auOAhlBfGfb9Dqkhhxmqp+IDo8OoU6Z8JmtvwmF1gyiKKmftJfj8OYOQs0NHxR8aL2LMSC3/+/E0X3rkFylMRXAY1eGkLVBQRzyUZPuvIxhjiZ/R/9JM2ZNB/pj2HoVKCpQQqQvTNtI0Vr89QH4/LkVOHtxkAKzuxuSUL2SCsDRXOiUkH/572hIVnm4jVgyW01XVLP+rKkP3rUGG47JoHMStflP5esfXxA9eTA4B0HNcVggWH6a7PXhxI/f8ZwqOC/cXyKSo5a7r3NY8fBrjvl5Kgt2BSf9tSKObHdpUdOjGubr4zs0qqDkyFwyP4YRG5smy1/72JapZNJjIo3lU/t2/+HBlQdlwYfUR8uG0q1YTg2tL9hZt9nxoBaETynbW8VrBp4PqiOUWdWQFdX2D8sGvi2QYZc6PRQFI6fRKfxJMru9+w0O/R4gmKJ3uWoe4NbWlCyubCWKK3UXTAs9GmqkY5Osv8U4eaXOnxNTUoCIbcJ+6erDtiVtmmTBKmk2KlSRt8u25s0Oj9/7XPa3lPg6g9zNvNhVe5a1qBvwAbEb2XRDksXhU=
  template:
    metadata:
      name: customer-db-secret
      namespace: default
