spring:
  datasource:
    url: jdbc:postgresql://account-postgres:5432/accountdb
    username: accountuser
    password: accountpass
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: bank-kafka:29092

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
