spring:
  application:
    name: card-service
  profiles:
    active: local

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


bank:
  card:
    default-validity-years: 3
    default-daily-limit: 5000.00
  security:
    argon2:
      salt-length: 16
      hash-length: 32
      parallelism: 1
      memory: 65536
      iterations: 3
    cvv-secret-key: "kP9!sA7zQ4#Lm82@VtR1wX$eH6^bN0fG"
