name: Account Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'account-service/**'
      - 'bank-common/**'

permissions:
  contents: write

jobs:
  call-template:
    uses: ./.github/workflows/template-microservice-ci.yml
    with:
      service_name: 'account-service'
      service_location: 'account'
    secrets: inherit