name: Ai Analyzer Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ai-analyzer-service/**'
      - 'bank-common/**'

jobs:
  call-template:
    uses: ./.github/workflows/template-microservice-ci.yml
    with:
      service_name: 'ai-analyzer-service'
    secrets: inherit