name: API Gateway CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api-gateway/**'
      - 'bank-common/**'
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  call-template:
    uses: ./.github/workflows/template-microservice-ci.yml
    with:
      service_name: 'api-gateway'
      service_location: 'api-gateway'
    secrets: inherit