name: Audit Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'audit-service/**'
      - 'bank-common/**'

jobs:
  call-template:
    uses: ./.github/workflows/template-microservice-ci.yml
    with:
      service_name: 'audit-service'
      service_location: 'audit'
    secrets: inherit