name: Auth Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'auth-service/**'
      - 'bank-common/**'

permissions:
  contents: write

jobs:
  call-template:
    uses: ./.github/workflows/template-microservice-ci.yml
    with:
      service_name: 'auth-service' #wstrzykiwana nazwa folderu
      service_location: 'auth'
    secrets: inherit # dostęp do sekretów
