name: Card Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'card-service/**'
      - 'bank-common/**'

jobs:
  call-template:
    uses: ./.github/workflows/template-microservice-ci.yml
    with:
      service_name: 'card-service'
    secrets: inherit