name: Notification Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'notification-service/**'
      - 'bank-common/**'
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  call-template:
    uses: ./.github/workflows/template-microservice-ci.yml
    with:
      service_name: 'notification-service'
      service_location: 'notification'
    secrets: inherit