name: Onboarding Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'onboarding-service/**'
      - 'bank-common/**'

jobs:
  call-template:
    uses: ./.github/workflows/template-microservice-ci.yml
    with:
      service_name: 'onboarding-service'
      service_location: 'onboarding'
    secrets: inherit